# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish hyperlaunch-cli.csproj
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v7.0.1
      with:
        name: linux-build
        path: bin/Release/net8.0/linux-x64/publish/
  windows-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish hyperlaunch-cli.csproj
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v7.0.1
      with:
        name: windows-build
        path: bin/Release/net8.0/win-x64/publish/
  mac-intel-build:
    runs-on: macos-15-intel
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish hyperlaunch-cli.csproj
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v7.0.1
      with:
        name: mac-intel-build
        path: bin/Release/net8.0/osx-x64/publish/
  mac-arm-build:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish hyperlaunch-cli.csproj
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v7.0.1
      with:
        name: mac-build
        path: bin/Release/net8.0/osx-arm64/publish/


